config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :bikes, only: %i[index show new create] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes, only: %i[index show]
  resources :user, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :name, :location, :size, :category, :price, presence: true
  validates :name, uniqueness: { scope: :user,
                                 message: "All your bikes should have a unique name" }
  validates :description, length: { minimum: 10,
                                    message: "Please add more detail to your bike description" }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates  :start_date, :end_date, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :start_date_cannot_be_after_end_date
  validates :start_date, uniqueness: { scope: :bike_id,
                                       message: "Sorry this bike has already been booked on this date" }
  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def start_date_cannot_be_after_end_date
    if start_date.present? && start_date > end_date
      errors.add(:start_date, "End date must be after start date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :bikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:home, :show, :index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
    @bikes = Bike.all
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike })
        # image_url: helpers.asset_url(Cloudinary::Utils.cloudinary_url(bike.photos.first.key))
      }
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @user = current_user
    @bike.user = @user
    @bike.save

    redirect_to bikes_path(@bike)
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :description, :category, :size, :location, :price, :user_id, photos: [])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @bike = Bike.find(params[:bike_id])
    @booking.bike = @bike
    @booking.user = current_user
    @booking.save
    redirect_to bike_path(@bike)
  end

  def show
      @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    @user = current_user

    redirect_to user_path(@user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :bike_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @bikes = Bike.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @bookings = current_user.bookings
    @bikes = current_user.bikes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<% if bike.photos.attached? %>
  <div class="info__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path bike.photos.first.key, height: 300, crop: :fill %>')"></div>
<% else %>
  <div class="info__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80)"></div>
<% end %>
<%= link_to bike.name, bike_path(bike), target: "_blank", class: "info__link" %>
<div class="info__list" >
  <p> <%= bike.category %> </p>
  <p> <%= bike.size %> </p>
  <p> <%= "£#{bike.price.to_i} per day" %> </p>
</div>

app/views/bikes/index.html.erb
  <div class="container">
    <div class="main-index">
      <%= render 'shared/cardgrid', locals: {bikes: @bikes} %>
      <div class="map">
        <div style="width: 100%; height: 600px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>

app/views/bikes/new.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-4">
        <%= simple_form_for @bike do |f| %>
          <%= f.input :name, label: 'Give your bike a name' %>
          <%= f.input :description %>
          <%= f.input :category, collection: ['Mountain', 'Road', 'Hybrid', 'Vintage', 'Electric'] %>
          <%= f.input :size, collection: ['Child', 'Small', 'Medium', 'Large', 'X-Large'] %>
          <%= f.input :location %>
          <%= f.input :price, collection: 0..100, label: 'Price per day(£)',   as: :float %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <div class="d-flex justify-content-center mb-3">
            <%= f.button :submit, class: "btn-flat" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="container pt-3">
  <div class="container-fluid pt-3">
    <div class="row">
      <div class="col-12 col-lg-8">
        <%= render "shared/carousel", locals: {bike: @bike} %>
        <h1 class="py-4"><%= @bike.name %></h1>
        <p><%= @bike.description %></p>
      </div>
      <div class="col-12 col-lg-4 pt-5">
              <h2>Book this bike</h2>
                <%= simple_form_for [ @bike, @booking ] do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
                <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
                <%= f.button :submit, class: "btn-flat" %>
                <% end %>
      </div>
    </div>
  </div>
</div>

<div class='map'>
  <script>
    // TO MAKE THE MAP APPEAR YOU MUST
    // ADD YOUR ACCESS TOKEN FROM
    // https://account.mapbox.com
    mapboxgl.accessToken = 'pk.eyJ1IjoiYW5keS1tb3J0b24iLCJhIjoiY2wxM2g3MnBvMXY0cjNqcnRlcHA3dXF3biJ9.JWTCD3YUE1scgDxTHeKK0w';
  const map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/streets-v11',
  center: [12.550343, 55.665957],
  zoom: 8
  });
</script>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [ @bike, @booking ] do |f| %>
  <%= f.input :start_date, as: :string %>
  <%= f.input :end_date, as: :string %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>My Bookings</h1>

    <li class="list-group-item"><%= @booking.user_id %></li>
    <li class="list-group-item"><%= @booking.price %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnbike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  </head>


  <body class="d-flex flex-column min-vh-100">
    <%= render 'shared/navbar' %>
    <div class="pt-5"></div>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <div class="mt-auto">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://giant-image-resizer-qu2qwwv2de7wv85rz.stackpathdns.com/remote/www.giant-bicycles.com/_upload/showcases/2017/liv-bikes/Banner_LangmaAdvancedSLShowcase.jpg);">
  <div class="container">
    <h1>Airbnbike </h1>
    <p>Find bikes to rent wherever you are</p>
    <%= link_to "Discover Bikes", bikes_path, class: "btn-flat" %>
  </div>
  <br><br>
</div>
  <div class="container mt-4">
    <%# <h2>Bikes available to rent</h2> %>
    <%= render 'shared/cardgrid_home', locals: {bikes: @bikes} %>
  </div>

app/views/shared/_cardgrid.html.erb
<ul class="row">
  <% @bikes.each do |bike| %>
    <div class="col-md-6 mb-3">
      <%= link_to bike_path(bike), class:"text-decoration-none" do %>
        <li class="cards__item">
          <div class="card">
            <% if bike.photos.attached? %>
              <div class="card__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path bike.photos.first.key, height: 300, crop: :fill %>')"></div>
            <% else %>
              <div class="card__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80)"></div>
            <% end %>
            <div class="card__content">
              <div class="card__header">
                <div class="card__title"><%= bike.name %></div>
                <% location = Geocoder.search(bike.location).first.suburb ? Geocoder.search(bike.location).first.suburb : Geocoder.search(bike.location).first.city %>
                <div class="card__location"><%= location %></div>
              </div>
              <div class="card__bottom">
                <div class="card__tab"><%= bike.category %></div>
                <div class="card__tab"><%= "#{bike.size}" %></div>
                <div class="card__tab cprice"><%= "£#{bike.price.to_i}/d" %></div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
      </div>
  <% end %>
</ul>

app/views/shared/_cardgrid_home.html.erb
<ul class="row">
  <% @bikes.each do |bike| %>
    <div class="col-md-4 mb-3">
      <%= link_to bike_path(bike), class:"text-decoration-none" do %>
        <li class="cards__item">
          <div class="card">
            <% if bike.photos.attached? %>
              <div class="card__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path bike.photos.first.key, height: 300, crop: :fill %>')"></div>
            <% else %>
              <div class="card__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80)"></div>
            <% end %>
            <div class="card__content">
              <div class="card__header">
                <div class="card__title"><%= bike.name %></div>
                <% location = Geocoder.search(bike.location).first.suburb ? Geocoder.search(bike.location).first.suburb : Geocoder.search(bike.location).first.city %>
                <div class="card__location"><%= location %></div>
              </div>
              <div class="card__bottom">
                <div class="card__tab"><%= bike.category %></div>
                <div class="card__tab"><%= "#{bike.size}" %></div>
                <div class="card__tab cprice"><%= "£#{bike.price.to_i}/d" %></div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
      </div>
  <% end %>
</ul>

app/views/shared/_carousel.html.erb
<% if @bike.photos.attached? %>
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% @bike.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %> ">
        <div class="carousel__image" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path photo.key, height: 300, crop: :fill %>')"></div>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<% else %>
  <%= image_tag("bike.jpg", style: 'display: block; margin: auto; width:90%;') %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    For the <i class="fas fa-heart"></i> of cycling
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div>
    <%= link_to "Airbnbike", root_path, class: "logo" %>
  </div>

 <% if user_signed_in? %>
  <div class="nav__links">
    <%= link_to "Search", bikes_path, class: "active nav__link" %>
    <%= link_to "My bookings", user_path(current_user), class: "nav__link" %>
    <%= link_to "List a bike", new_bike_path, class: "nav__link" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav__link" %>
  </div>
<% else %>

   <%= link_to "Login", new_user_session_path, class: "nav__link" %>

<% end %>

<script src="main.js"></script>
</div>

app/views/user/show.html.erb
<div class="container pt-3">
  <h3 class>Your Bookings:</h3>
  <hr>
    <div class="row">
      <% @bookings.each do |booking| %>
         <div class="col-md-4 mb-3">
           <% if booking.bike.photos.attached? %>
                <div class="card-product">
                  <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3),
                              rgba(0,0,0,0.3)),
                              url('<%= cl_image_path booking.bike.photos.first.key, height: 300, crop: :fill %>')"></div>
                  <div class="card-product-infos">
                        <p><%= "Total Days: #{((booking.end_date - booking.start_date).to_i)+1}" %></p>
                        <p><%= "Total Cost: £#{booking.bike.price * (((booking.end_date - booking.start_date).to_i)+1) }" %></p>
                        <p><%= "#{booking.start_date} -> #{booking.end_date}" %></p>
                        <% location = Geocoder.search(booking.bike.location).first.suburb ? Geocoder.search(booking.bike.location).first.suburb : Geocoder.search(booking.bike.location).first.city %>
                        <p><%= "Pick up in #{location}" %></p>
                        <%= link_to "",
                        booking_path(booking),
                        method: :delete,
                        data: { confirm: "Are you sure?" },
                        class: "fa-regular fa-trash-can" %>
                  </div>
                </div>
           <% else %>
              <div class="card-product">
                  <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80)"></div>
                <div class="card-product-infos">
                <p><%= "Number of days: #{((booking.end_date - booking.start_date).to_i)+1}" %></p>
                  <p><%= "Price: #{booking.bike.price * (((booking.end_date - booking.start_date).to_i)+1) }" %></p>
                  <%= link_to "Delete #{booking.bike.name}",
                  booking_path(booking),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
                </div>
              </div>
            <% end %>
          </div>
         <% end %>
      </div>
    </div>

  <div class="container pt-3">
    <h3 class="text-black">Your Bikes:</h3>
    <hr>
    <div class="row">
      <% @bikes.each do |bike| %>
        <div class="col-md-4 mb-3">
          <div class="flip-card">
            <div class="flip-card-inner">
              <div class="flip-card-front">
                  <%= link_to bike_path(bike), class:"text-decoration-none" do %>
                      <% if bike.photos.attached? %>
                        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path bike.photos.first.key, height: 300, crop: :fill %>')">
                          <%= bike.name %>
                        </div>
                      <% else %>
                        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80)">
                          <%= bike.name %>
                        </div>
                      <% end %>
                  <% end%>
              </div>
              <div class="flip-card-back">
                <%= "Total bookings made for this bike:" %>
                <%= bike.bookings.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>